### ISSUE TITLE
Adding more synced fields?

### ISSUE THREAD

**Issue by Yoozed** [Fullstak-BV/laposta-elementor-forms#1]
Hi, really great that you made this plugin. 

Question/request: would it be possible to add more synced fields (name, for instance) to the functionality?

Thanks in advance!

**Comment by breakerh** [comment]
Sorry for the long wait.
Just updated the plugin. It's now possible to map all fields from your list to the form fields :)

**Comment by Yoozed** [comment]
Very much appreciated, thank you!
